// <auto-generated />
using System;
using FlowMeter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlowMeter.Data.Migrations
{
    [DbContext(typeof(FlowMeterDbContext))]
    [Migration("20220217214920_PipesShapes2")]
    partial class PipesShapes2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlowMeter.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeviceNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("FlowMeter.Domain.Localization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CanalRadius")
                        .HasColumnType("float");

                    b.Property<decimal>("GpsCoordinate1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GpsCoordinate2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("FlowMeter.Domain.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AverageFlow")
                        .HasColumnType("float");

                    b.Property<string>("Battery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CurrentFlow")
                        .HasColumnType("float");

                    b.Property<bool>("IsSpecialPoint")
                        .HasColumnType("bit");

                    b.Property<double>("Pressure")
                        .HasColumnType("float");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("FlowMeter.Domain.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("FlowMeter.Domain.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("FlowMeter.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FlowMeter.Domain.Shapes.Circle", b =>
                {
                    b.HasBaseType("FlowMeter.Domain.Shape");

                    b.Property<double?>("Radius")
                        .HasColumnType("float");

                    b.ToTable("Circles");
                });

            modelBuilder.Entity("FlowMeter.Domain.Shapes.Rectangle", b =>
                {
                    b.HasBaseType("FlowMeter.Domain.Shape");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<double?>("Lenght")
                        .HasColumnType("float");

                    b.ToTable("Rectangles");
                });

            modelBuilder.Entity("FlowMeter.Domain.Shapes.Trapezium", b =>
                {
                    b.HasBaseType("FlowMeter.Domain.Shape");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<double?>("LengthA")
                        .HasColumnType("float");

                    b.Property<double?>("LengthB")
                        .HasColumnType("float");

                    b.ToTable("Trapeziums");
                });

            modelBuilder.Entity("FlowMeter.Domain.Device", b =>
                {
                    b.HasOne("FlowMeter.Domain.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowMeter.Domain.Measurement", b =>
                {
                    b.HasOne("FlowMeter.Domain.Survey", "Survey")
                        .WithMany("Measurements")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FlowMeter.Domain.Survey", b =>
                {
                    b.HasOne("FlowMeter.Domain.Device", "Device")
                        .WithMany("Surveys")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowMeter.Domain.Localization", "Localization")
                        .WithMany("Surveys")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("FlowMeter.Domain.Shapes.Circle", b =>
                {
                    b.HasOne("FlowMeter.Domain.Shape", null)
                        .WithOne()
                        .HasForeignKey("FlowMeter.Domain.Shapes.Circle", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowMeter.Domain.Shapes.Rectangle", b =>
                {
                    b.HasOne("FlowMeter.Domain.Shape", null)
                        .WithOne()
                        .HasForeignKey("FlowMeter.Domain.Shapes.Rectangle", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowMeter.Domain.Shapes.Trapezium", b =>
                {
                    b.HasOne("FlowMeter.Domain.Shape", null)
                        .WithOne()
                        .HasForeignKey("FlowMeter.Domain.Shapes.Trapezium", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowMeter.Domain.Device", b =>
                {
                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("FlowMeter.Domain.Localization", b =>
                {
                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("FlowMeter.Domain.Survey", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("FlowMeter.Domain.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
